theme: jekyll-theme-minimal
description: This is my blog to document the trials and tribulations of my cyber journey.

author:
  name:       "Cramer McGarr"
  avatar:     "/img/avatar.png"
  linkedin:   "cramer-mcgarr/"
